M:test_screen
F:G$screen_test_screen_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$screen_test_screen_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltest_screen.screen_test_screen_update$screen_type$1$9({2}DG,SC:U),B,1,4
S:Ltest_screen.screen_test_screen_update$input1$1$10({1}SC:U),R,0,0,[]
S:G$riff_sample_data$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_update$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_hold$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move$0$0({2}DF,SC:U),C,0,0
S:G$engine_riff_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_riff_manager_play$0$0({2}DF,SV:S),C,0,0
